import './globals.css'
import { Roboto } from 'next/font/google';
import Header from './components/Header'

export const metadata = {
  title: 'Movie App using Next js',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
